name: Docker
on:
  schedule:
    - cron: '24 21 * * *'
  push:
    branches: [ master ]
    # Publish semver tags as releases.
    tags: [ 'v*.*.*' ]
  pull_request:
    branches: [ master ]

jobs:
  build:

    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1

      - name: Log into registry ghcr.io
        if: github.event_name != 'pull_request'
        uses: docker/login-action@v1
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Log into registry docker.io
        if: github.event_name != 'pull_request'
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Extract Docker metadata from ghcr.io
        id: ghcr-io-meta
        uses: docker/metadata-action@v3
        with:
          images: ghcr.io/hellyna/docker-socket-proxy

      - name: Extract Docker metadata from docker.io
        id: docker-io-meta
        uses: docker/metadata-action@v3
        with:
          images: docker.io/quiexotic/ddocker-socket-proxy

      - name: Build and push Docker image to ghcr.io
        uses: docker/build-push-action@v2
        with:
          context: .
          push: ${{ github.event_name != 'pull_request' }}
          tags: ${{ steps.ghcr-io-meta.outputs.tags }}
          labels: ${{ steps.ghcr-io-meta.outputs.labels }}

      - name: Build and push Docker image to docker.io
        uses: docker/build-push-action@v2
        with:
          context: .
          push: ${{ github.event_name != 'pull_request' }}
          tags: ${{ steps.docker-io-meta.outputs.tags }}
          labels: ${{ steps.docker-io-meta.outputs.labels }}
